num1=float(input("Enter the first number:"))
num2=float(input("Enter the second number:"))
print("The sum of two numbers is:",num1+num2)
print("The subtraction of two numbers is:",num1-num2)
print("The multiplication of two numbers is:",num1*num2)
print("The division of two numbers is:",num1/num2)